// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.5
// 	protoc        v3.21.12
// source: pkg/perftest/perftest.proto

package perftest

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PortRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PortRequest) Reset() {
	*x = PortRequest{}
	mi := &file_pkg_perftest_perftest_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PortRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PortRequest) ProtoMessage() {}

func (x *PortRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_perftest_perftest_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PortRequest.ProtoReflect.Descriptor instead.
func (*PortRequest) Descriptor() ([]byte, []int) {
	return file_pkg_perftest_perftest_proto_rawDescGZIP(), []int{0}
}

type PortResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Value         int32                  `protobuf:"varint,1,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PortResponse) Reset() {
	*x = PortResponse{}
	mi := &file_pkg_perftest_perftest_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PortResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PortResponse) ProtoMessage() {}

func (x *PortResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_perftest_perftest_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PortResponse.ProtoReflect.Descriptor instead.
func (*PortResponse) Descriptor() ([]byte, []int) {
	return file_pkg_perftest_perftest_proto_rawDescGZIP(), []int{1}
}

func (x *PortResponse) GetValue() int32 {
	if x != nil {
		return x.Value
	}
	return 0
}

type PerftestRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Port          int32                  `protobuf:"varint,1,opt,name=port,proto3" json:"port,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PerftestRequest) Reset() {
	*x = PerftestRequest{}
	mi := &file_pkg_perftest_perftest_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PerftestRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PerftestRequest) ProtoMessage() {}

func (x *PerftestRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_perftest_perftest_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PerftestRequest.ProtoReflect.Descriptor instead.
func (*PerftestRequest) Descriptor() ([]byte, []int) {
	return file_pkg_perftest_perftest_proto_rawDescGZIP(), []int{2}
}

func (x *PerftestRequest) GetPort() int32 {
	if x != nil {
		return x.Port
	}
	return 0
}

type PerftestResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PerftestResponse) Reset() {
	*x = PerftestResponse{}
	mi := &file_pkg_perftest_perftest_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PerftestResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PerftestResponse) ProtoMessage() {}

func (x *PerftestResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_perftest_perftest_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PerftestResponse.ProtoReflect.Descriptor instead.
func (*PerftestResponse) Descriptor() ([]byte, []int) {
	return file_pkg_perftest_perftest_proto_rawDescGZIP(), []int{3}
}

func (x *PerftestResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_pkg_perftest_perftest_proto protoreflect.FileDescriptor

var file_pkg_perftest_perftest_proto_rawDesc = string([]byte{
	0x0a, 0x1b, 0x70, 0x6b, 0x67, 0x2f, 0x70, 0x65, 0x72, 0x66, 0x74, 0x65, 0x73, 0x74, 0x2f, 0x70,
	0x65, 0x72, 0x66, 0x74, 0x65, 0x73, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x08, 0x70,
	0x65, 0x72, 0x66, 0x74, 0x65, 0x73, 0x74, 0x22, 0x0d, 0x0a, 0x0b, 0x50, 0x6f, 0x72, 0x74, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x24, 0x0a, 0x0c, 0x50, 0x6f, 0x72, 0x74, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x22, 0x25, 0x0a, 0x0f,
	0x50, 0x65, 0x72, 0x66, 0x74, 0x65, 0x73, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12,
	0x12, 0x0a, 0x04, 0x70, 0x6f, 0x72, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x70,
	0x6f, 0x72, 0x74, 0x22, 0x2c, 0x0a, 0x10, 0x50, 0x65, 0x72, 0x66, 0x74, 0x65, 0x73, 0x74, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61,
	0x67, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67,
	0x65, 0x32, 0x90, 0x01, 0x0a, 0x08, 0x50, 0x65, 0x72, 0x66, 0x74, 0x65, 0x73, 0x74, 0x12, 0x3a,
	0x0a, 0x07, 0x47, 0x65, 0x74, 0x50, 0x6f, 0x72, 0x74, 0x12, 0x15, 0x2e, 0x70, 0x65, 0x72, 0x66,
	0x74, 0x65, 0x73, 0x74, 0x2e, 0x50, 0x6f, 0x72, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x1a, 0x16, 0x2e, 0x70, 0x65, 0x72, 0x66, 0x74, 0x65, 0x73, 0x74, 0x2e, 0x50, 0x6f, 0x72, 0x74,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x48, 0x0a, 0x0d, 0x53, 0x74,
	0x61, 0x72, 0x74, 0x50, 0x65, 0x72, 0x66, 0x74, 0x65, 0x73, 0x74, 0x12, 0x19, 0x2e, 0x70, 0x65,
	0x72, 0x66, 0x74, 0x65, 0x73, 0x74, 0x2e, 0x50, 0x65, 0x72, 0x66, 0x74, 0x65, 0x73, 0x74, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1a, 0x2e, 0x70, 0x65, 0x72, 0x66, 0x74, 0x65, 0x73,
	0x74, 0x2e, 0x50, 0x65, 0x72, 0x66, 0x74, 0x65, 0x73, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x22, 0x00, 0x42, 0x31, 0x5a, 0x2f, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63,
	0x6f, 0x6d, 0x2f, 0x70, 0x61, 0x64, 0x64, 0x79, 0x6f, 0x6e, 0x65, 0x69, 0x6c, 0x6c, 0x2f, 0x70,
	0x65, 0x72, 0x66, 0x74, 0x65, 0x73, 0x74, 0x2d, 0x67, 0x6f, 0x2f, 0x70, 0x6b, 0x67, 0x2f, 0x70,
	0x65, 0x72, 0x66, 0x74, 0x65, 0x73, 0x74, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
})

var (
	file_pkg_perftest_perftest_proto_rawDescOnce sync.Once
	file_pkg_perftest_perftest_proto_rawDescData []byte
)

func file_pkg_perftest_perftest_proto_rawDescGZIP() []byte {
	file_pkg_perftest_perftest_proto_rawDescOnce.Do(func() {
		file_pkg_perftest_perftest_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pkg_perftest_perftest_proto_rawDesc), len(file_pkg_perftest_perftest_proto_rawDesc)))
	})
	return file_pkg_perftest_perftest_proto_rawDescData
}

var file_pkg_perftest_perftest_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_pkg_perftest_perftest_proto_goTypes = []any{
	(*PortRequest)(nil),      // 0: perftest.PortRequest
	(*PortResponse)(nil),     // 1: perftest.PortResponse
	(*PerftestRequest)(nil),  // 2: perftest.PerftestRequest
	(*PerftestResponse)(nil), // 3: perftest.PerftestResponse
}
var file_pkg_perftest_perftest_proto_depIdxs = []int32{
	0, // 0: perftest.Perftest.GetPort:input_type -> perftest.PortRequest
	2, // 1: perftest.Perftest.StartPerftest:input_type -> perftest.PerftestRequest
	1, // 2: perftest.Perftest.GetPort:output_type -> perftest.PortResponse
	3, // 3: perftest.Perftest.StartPerftest:output_type -> perftest.PerftestResponse
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_pkg_perftest_perftest_proto_init() }
func file_pkg_perftest_perftest_proto_init() {
	if File_pkg_perftest_perftest_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pkg_perftest_perftest_proto_rawDesc), len(file_pkg_perftest_perftest_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pkg_perftest_perftest_proto_goTypes,
		DependencyIndexes: file_pkg_perftest_perftest_proto_depIdxs,
		MessageInfos:      file_pkg_perftest_perftest_proto_msgTypes,
	}.Build()
	File_pkg_perftest_perftest_proto = out.File
	file_pkg_perftest_perftest_proto_goTypes = nil
	file_pkg_perftest_perftest_proto_depIdxs = nil
}
